### PR TITLE
Update recipe

### PR DESCRIPTION
**Pull request by npavlovikj**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by npavlovikj** [comment]
@dpryan79 , @cbrueffer , this looks ok to you two? I was told in the CF gitter channel not to ignore the error and not to use version constraints for non noarch recipes.

**Comment by cbrueffer** [comment]
Looks good, thanks! Can we relax the version requirement to just 3.5 to be a bit more generic?

**Comment by npavlovikj** [comment]
The initial error with the newer version was that `ERROR: this R is version 3.5.1, package 'depmixS4' requires R >= 3.6.0`, thus we need to skip 3.5.

**Comment by cbrueffer** [comment]
Right; what I mean is changing it to `skip: True  # [r_base == "3.5*"]` to make the match independent of patch level; shouldn't matter functionality-wise, but may be a nicer pattern for future reference. What do you think?

**Comment by npavlovikj** [comment]
> Right; what I mean is changing it to `skip: True # [r_base == "3.5*"]` to make the match independent of patch level; shouldn't matter functionality-wise, but may be a nicer pattern for future reference. What do you think?

Ah, thank you for the clarification, that makes more sense now :) Yes, that is a good idea - I updated this PR accordingly.

**Comment by cbrueffer** [comment]
Looks great, please merge!

**Comment by npavlovikj** [comment]
Thank you for the feedback and review @cbrueffer !

**Pull request merged**
